### ISSUE TITLE
The id is empty! Please provide a valid id.

### ISSUE THREAD

**Issue by tobasium** [simatec/ioBroker.shuttercontrol#288]
Adapter startet nach Update immer wieder neu. Alle 5 min

folgende Fehler finde ich im Logfile:

`
2021-12-01 10:20:02.383 - error: shuttercontrol.0 (6217) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-12-01 10:20:02.385 - error: shuttercontrol.0 (6217) unhandled promise rejection: The id is empty! Please provide a valid id.
2021-12-01 10:20:02.470 - error: shuttercontrol.0 (6217) Error: The id is empty! Please provide a valid id.
at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:501:19)
at Adapter.getForeignState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6815:17)
at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1652:16
at new Promise ()
at Adapter.getForeignStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1651:16)
at /opt/iobroker/node_modules/iobroker.shuttercontrol/lib/shutterAlarm.js:672:83
at new Promise ()
at checkPendingAlarm (/opt/iobroker/node_modules/iobroker.shuttercontrol/lib/shutterAlarm.js:661:12)
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.shuttercontrol/lib/sunProtect.js:30:56)
at listOnTimeout (internal/timers.js:557:17)
2021-12-01 10:20:02.489 - error: shuttercontrol.0 (6217) The id is empty! Please provide a valid id.
2021-12-01 10:20:02.565 - error: shuttercontrol.0 (6217) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-12-01 10:20:02.574 - error: shuttercontrol.0 (6217) unhandled promise rejection: The id is empty! Please provide a valid id.
2021-12-01 10:20:02.575 - error: shuttercontrol.0 (6217) Error: The id is empty! Please provide a valid id.
at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:501:19)
at Adapter.getForeignState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6815:17)
at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1652:16
at new Promise ()
at Adapter.getForeignStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1651:16)
at /opt/iobroker/node_modules/iobroker.shuttercontrol/lib/shutterAlarm.js:672:83
at new Promise ()
at checkPendingAlarm (/opt/iobroker/node_modules/iobroker.shuttercontrol/lib/shutterAlarm.js:661:12)
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.shuttercontrol/lib/sunProtect.js:30:56)
at listOnTimeout (internal/timers.js:557:17)
2021-12-01 10:20:02.585 - error: shuttercontrol.0 (6217) The id is empty! Please provide a valid id.
2021-12-01 10:20:02.696 - info: shuttercontrol.0 (6217) cleaned everything up...
2021-12-01 10:20:02.698 - info: shuttercontrol.0 (6217) terminating
2021-12-01 10:20:02.700 - debug: shuttercontrol.0 (6217) Plugin sentry destroyed
2021-12-01 10:20:02.700 - warn: shuttercontrol.0 (6217) Terminated (UNCAUGHT_EXCEPTION): Without reason
`

**Versions:**  
 - Adapter version: 1.4.0
 - JS-Controller version: 3.3.21
 - Node version: v14.18.2
 - NPM: 6.14.15
 - Operating system: Docker

**Comment by simatec** [comment]
Fehler ist in Version 1.4.1 gefixt. Bitte updaten

**Comment by tobasium** [comment]
Super, das scheint zu laufen.

Vielen Dank für den schnellen FIX
